landmarks = dict()
landmarks['nose'] = 0 
landmarks['left eye'] = 1
landmarks['right eye'] = 2
landmarks['left ear'] = 3
landmarks['right ear'] = 4
landmarks['left shoulder'] = 5 
landmarks['right shoulder'] = 6
landmarks['left elbow'] = 7
landmarks['right elbow'] = 8
landmarks['left wrist'] = 9
landmarks['right wrist'] = 10
landmarks['left hip'] = 11
landmarks['right hip'] = 12
landmarks['left knee'] = 13
landmarks['right knee'] = 14
landmarks['left ankle'] = 15
landmarks['right ankle'] = 16
